---
- name: Deploy the infrastructure to execute and restore backups
  hosts: desenvolvimento,producao
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'Install python3 and pip'
      raw: apt-get -y install python3-pip python3-setuptools
  tasks:
    - name: Cria a pasta backups
      become: yes
      become_user: root
      file: path=/opt/backups/ state=directory mode=0755 owner=odoo
    - name: Cria a pasta .aws
      become: yes
      become_user: root
      file: path=/home/odoo/.aws/ state=directory mode=0755 owner=odoo
    - copy:
        src: scripts/common.py
        dest: /opt/backups/common.py
        owner: odoo
        group: odoo
        mode: 0644
    - copy:
        src: scripts/odoo_restore.py
        dest: /opt/backups/odoo-restore.py
        owner: odoo
        group: odoo
        mode: 0644
    - copy:
        src: scripts/odoo_backup.py
        dest: /opt/backups/odoo-backup.py
        owner: odoo
        group: odoo
        mode: 0644
    - template:
        src: templates/aws.credentials
        dest: /home/odoo/.aws/credentials
        owner: odoo
        group: odoo
        mode: 0644
    - template:
        src: templates/aws.config
        dest: /home/odoo/.aws/config
        owner: odoo
        group: odoo
        mode: 0644
    - pip:
        executable: pip3
        name: "{{ item }}"
        state: present
      with_items:
        - awscli
        - docopt
        - psycopg2
        - boto3
    - cron:
        name: "Execute backup scripts"
        user: "odoo"
        hour: "04"
        minute: "45"
        job: "python3 /opt/backups/odoo-backup.py {{ pg_user }} {{ pg_password }}"
      when: inventory_hostname in groups['producao']
