---
- name: Inicializa uma nova base de dados - Utilizar somente quando o docker jรก existir
  hosts: desenvolvimento,producao
  become: yes
  vars_prompt:
    - name: "module_update"
      prompt: "Digite o modulo a atualizar"
      private: no

  roles:
    - odoo-new
