---
- name: Deploy an complete Odoo Installation
  hosts: desenvolvimento,producao
  become: yes
  vars_prompt:
    - name: "module_update"
      prompt: "Digite o modulo a atualizar"
      private: no

  roles:
    - odoo
