---
- name: Deploy the infrastructure to execute and restore backups
  hosts: desenvolvimento,producao
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'Install python2'
      raw: apt-get -y install python-simplejson
  tasks:
    - copy:
        src: scripts/restore_backup_s3.py
        dest: /opt/backups/restore_backup_s3.py
        owner: odoo
        group: odoo
        mode: 0644
    - copy:
        src: scripts/restore_backup_s3.py
        dest: /opt/backups/odoo-backup.py
        owner: odoo
        group: odoo
        mode: 0644
    - template:
        src: templates/aws.credentials
        dest: ~/.aws/credentials
        owner: odoo
        group: odoo
        mode: 0644
    - template:
        src: templates/aws.config
        dest: ~/.aws/config
        owner: odoo
        group: odoo
        mode: 0644
    - pip:
        name: awscli

    - cron:
        name: "Execute backup scripts"
        minute: "0"
        hour: "5,2"
        job: "python3 /opt/backups/odoo-backup.py"
