---
- name: Preparando goAccess
  hosts: producao
  become: yes

  tasks:
    - name: goAccess | Dependencia ncurses
      apt: pkg={{ item }} state=installed force=yes
      with_items:
        - libncursesw5-dev

    - name: goAccess | Fazendo o download
      get_url:
          url: http://tar.goaccess.io/goaccess-1.1.1.tar.gz
          dest: ~/goaccess.tar.gz
    - name: goAccess | Descompactando
      unarchive:
          remote_src: yes
          src: ~/goaccess.tar.gz
          dest: ~/
    - name: goAccess | pre-build configure
      command: ./configure --enable-utf8 chdir=~/goaccess-1.1.1
    - name: goAccess | Compilando
      command: make chdir=~/goaccess-1.1.1
