---
- name: Prepare server
  hosts: desenvolvimento:producao
  become: yes
  gather_facts: no
  vars:
    user_odoo_password: "{{ lookup('password', '~/ansible/odoo-user-password chars=ascii_letters,digits') }}"
  pre_tasks:
    - name: 'Install python2'
      raw: apt-get -y install python-simplejson

  tasks:
    - name: Configura usuário padrão
      user:
        name: odoo
        uid: 1040
        shell: /bin/bash
        groups: sudo
        append: yes
        password: "{{user_odoo_password}}"
