---
  - name: Create DB (if necessary)
    become: yes
    become_user: postgres
    postgresql_db:
        name: "{{ item }}"
        owner: "{{ pg_user }}"
        state: present
        template: "template0"
        port: "{{ pg_port }}"
    register: dbstatus
    with_items: "{{ databases }}"

  - name: Deleta o docker odoo de update
    become: yes
    become_user: odoo
    docker_container:
      name: "trustcode-update-odoo-{{ item }}"
      state: absent
    with_items: "{{ databases }}"

  - name: Inicia o docker odoo e inicializa a base de dados
    become: yes
    become_user: odoo
    command: "docker run --name trustcode-update-odoo-{{ item.key }} --net host -v /opt/dados/{{ item.value.docker.name }}:/opt/dados trustcode/docker-odoo:{{ item.value.docker.versao }} /usr/bin/odoo-server -c /etc/odoo/odoo.conf -d {{ item.key }} -i br_base -r {{ pg_user }} --db_port {{ pg_port }} -w {{ pg_password }} --without-demo=all --stop-after-init"
    when: dbstatus.changed
    with_dict: "{{ databases }}"

  - name: Recria o docker odoo
    become: yes
    become_user: odoo
    docker_container:
      name: trustcode-odoo-{{ item.key }}
      image: trustcode/docker-odoo:{{ item.value.versao }}
      network_mode: host
      restart: yes
      state: started
      recreate: yes
      volumes:
        - "/opt/dados/{{ item.key }}:/opt/dados"
      env:
        PG_PORT: "{{ pg_port }}"
        PG_USER: "{{ pg_user }}"
        PG_PASSWORD: "{{ pg_password }}"
        PORT: "{{ item.value.porta }}"
        LONGPOLLING_PORT: "{{ item.value.porta_polling }}"
        WORKERS: "{{ workers }}"
    with_dict: "{{ docker }}"

  - name: Modifica a senha padrão
    become: yes
    become_user: odoo
    command: "docker exec -u root trustcode-odoo-{{ item.key }} sed -i 's/senha_admin/{{ item.value.admin_password }}/' /etc/odoo/odoo.conf"
    when: inventory_hostname in groups['producao']
    with_dict: "{{ docker }}"

  - name: Adicionando dbfilter ao arquivo de configuração
    become: yes
    become_user: odoo
    command: docker exec -u root trustcode-odoo-{{ item.key }} bash -c "echo 'dbfilter = ^%d' >> /etc/odoo/odoo.conf"
    when: inventory_hostname in groups['trustcode']
    with_dict: "{{ docker }}"

  - name: Reinicia o odoo via supervisor para pegar nova senha
    become: yes
    become_user: odoo
    command: "docker exec trustcode-odoo-{{ item.key }} supervisorctl restart odoo"
    when: inventory_hostname in groups['producao']
    with_dict: "{{ docker }}"

  - name: Nginx | Criar configuracao
    template:
      src: "nginx-ssl-pre.j2"
      dest: "/etc/nginx/sites-available/{{ item.key }}"
      owner: root
      group: root
      mode: 0755
    with_dict: "{{ databases }}"
    when: inventory_hostname in groups['producao']

  - name: Nginx | Link para habilitar o site
    file:
      src: "/etc/nginx/sites-available/{{ item.key }}"
      dest: "/etc/nginx/sites-enabled/{{ item.key }}"
      state: link
    with_dict: "{{ databases }}"
    when: inventory_hostname in groups['producao']

  - name: Certbot - Cria certificados
    become: yes
    become_user: root
    command: "certbot certonly --authenticator standalone --installer nginx -n --expand --agree-tos --email secure@trustcode.com.br --redirect -d {{ ','.join(item.value.domain) }} --pre-hook 'service nginx stop' --post-hook 'service nginx start'"
    when: inventory_hostname in groups['producao'] and inventory_hostname not in groups['ssloff']
    with_dict: "{{ databases }}"

  - name: Nginx | Criar configuracao
    template:
      src: "nginx-ssl-pos.j2"
      dest: "/etc/nginx/sites-available/{{ item.key }}"
      owner: root
      group: root
      mode: 0755
    with_dict: "{{ databases }}"
    when: inventory_hostname in groups['producao'] and inventory_hostname not in groups['ssloff']

  - name: Nginx | Assegurar que Nginx esta instalado (package)
    service:
      name: nginx
      state: restarted
    when: inventory_hostname in groups['producao']
