---

- name: Run the fucking locales
  command: locale-gen en_US en_US.UTF-8 pt_BR pt_BR.UTF-8

- name: Seta Locale Brasil
  command: update-locale LC_ALL=pt_BR.UTF-8

- name: set default locale
  become: yes
  lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"pt_BR.UTF-8\""

- name: set default locale environment
  become: yes
  lineinfile: dest=/etc/environment
    regexp="LC_ALL"
    line="LC_ALL=\"pt_BR.UTF-8\""

- name: Install postgres
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql-common
    - postgresql-contrib
    - postgresql
    - libpq-dev
    - python-psycopg2
  tags:
    - packages

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

- name: Local PostgreSQL - Active the 'unaccent' extension on databases
  become: yes
  become_user: postgres
  postgresql_ext: name=unaccent db=template1 port={{ pg_port }}

- name: Postgres - Adjust configuration parameters
  blockinfile:
    path: /etc/postgresql/9.5/main/postgresql.conf
    marker: "# {mark} Tunning postgres configuration"
    block: |
        max_connections = 200
        shared_buffers = 1GB
        effective_cache_size = 3GB
        work_mem = 5242kB
        maintenance_work_mem = 256MB
        min_wal_size = 1GB
        max_wal_size = 2GB
        checkpoint_completion_target = 0.7
        wal_buffers = 16MB
        default_statistics_target = 100

- name: Postgres | Restart service to get new configuration
  service:
    name: postgresql
    state: restarted
